# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
        FOLDERS: "Prime Echoes CGC"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Set environment variables
        run: |
          export LANG=C
          month_short=$(date +%b) 
          month_long=$(date +%B) 
          year=$(date +%Y)
          
          month_short="${month_short,,}"
          month_long="${month_long,,}"
          
          echo "MONTH_SHORT=$month_short" >> $GITHUB_ENV
          echo "MONTH_LONG=$month_long" >> $GITHUB_ENV
          echo "YEAR=$year" >> $GITHUB_ENV

      - name: echo test
        run: |
          echo $MONTH_SHORT
          echo $MONTH_LONG
          echo $YEAR
          echo $FOLDERS
          
      - name: Rename Presets in preperation for upload
        run: |
          
          for subfolder in "${FOLDERS[@]}"
          do
            for f in ./$subfolder/*.rdvpreset
            do
              echo $f
              mv $f ${f/current/"$MONTH_LONG-$YEAR"}
            done
          done
          tree .

      - name: Create zips
        run: |
        

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
